program rfa_program
! Compilation:
! gfortran input_rfa_pb.f90 photosynthesis.o -o input_rfa_pb 

!========================= Interface files ========================================================
! Input files:
!          1. parameters.dat
! Output files:
!          1. input.dat
!
! ==================  Purpose and main tasks ======================================================
! Purpose: Creates a file with RFA x photosynthesis to be used for testing optimzations
! Steps: 
!     1. RFA is genetatend randomly between xx and yy
!     2. Photosynhesys is simulated with function given in QCANE model
!     3. Parameters are read from "parameters.dat" with tutill library
!     4. In "parameters.dat" is also informed which parameters will be optmized
!     5. Files are save into "input.dat", which is used as the "measured" values in optimizations"
!==================================================================================================

implicit none
integer i
real*8 r,RFA,IAF
real*8 fotosynD,Nl

! Parameters for the photosynthesis subroutine
real*8::  An1 
real*8::  Bn1 
real*8::  Apm 
real*8::  Bpm 
real*8::  Cpm 
real*8::  Dpm 
real*8::  coTF 
real*8::  alpha 
real*8::  Kext  

character(8)  :: date
character(10) :: time
character(5)  :: zone
integer,dimension(8) :: values
integer:: stat
character(10):: dummychar

! using keyword arguments
call date_and_time(date,time,zone,values)

! Reading input parameter file
! Open the file form tuttil subroutine
call rdinit(10,20,"parameters.dat")



call rdsdou("An1",An1)
call rdsdou("Bn1",Bn1) 
call rdsdou("Apm",Apm) 
call rdsdou("Bpm",Bpm) 
call rdsdou("Cpm",Cpm) 
call rdsdou("Dpm",Dpm) 
call rdsdou("CoTF",CoTF) 
call rdsdou("alpha",alpha) 
call rdsdou("kext",kext) 
call rdsdou("IAF",IAF) 
! Closing the files from tuttil
close(10) ; close(20)
call RDDTMP(100)

! Deleting the created file
open(20,file="fort.20",status="old")
if (stat == 0)  close(20,status="delete")


open(1,file = "input.dat",status="replace")

write(1,"(a)")"*--Photosyntheically active radation and daily gross photosynthesis--"
write(1,"(a)")"*Generated by input_rfa_pb.f90 program on "//date(7:8)//"/"//date(5:6)//&
            &"/"//date(1:4)//" at "//time(1:2)//":"//time(3:4)//":"//time(5:6)

write(1,"(2A)")"*",repeat("-",22)
write(1,*) "  RFA           PB  "
write(1,"(2A)")"* MJ/m2/d   g CO2/m2 ",repeat("-",2)


! Initial values of parameters to be evaluated

IAF = 3.0d0

do i = 1,100
  call random_seed()
  call random_number(r)
  r = 10*( r - 0.5)
  RFA =  (10d0 + r)
  call pb(An1,Bn1,Apm,Bpm,Cpm,Dpm,coTF,alpha,Kext,IAF,RFA*1e6,fotosynD,Nl)
  write(1,"(F10.7,2x,f10.5)")RFA,fotosynD

enddo

! Wrinting the values of parameters
write(1,"(a)")"*"//repeat("-",20)
write(1,"(A,F10.5)")"An1 = ",An1
write(1,"(A,F10.5)")"Bn1 = ",Bn1
write(1,"(A,F10.5)")"Apm = ",Apm
write(1,"(A,E11.5)")"Bpm = ",Bpm
write(1,"(A,F10.5)")"Cpm = ",Cpm
write(1,"(A,F10.5)")"Dpm = ",Dpm
write(1,"(A,F10.5)")"coTF = ",coTF
write(1,"(A,E11.5)")"alpha = ",alpha
write(1,"(A,F10.5)")"Kext = ",Kext
write(1,"(A,F10.5)")"IAF = ",IAF

close(1)

print*,"Program finished. Saved files:"
print*,"input.dat"



end
